### ISSUE TITLE
Incomplete Activity/History information

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#255]
We need to re-think the way we populate the history list and the run log, right now both are populated from a call to `/activity` which only includes the most recent 25 results mixed together.

- It looks like `/activity` doesn't accept pagination parameters
- Lack of pagination aside, we are also using this response to populate the total counts (total versions of a dataset, total number of runs in a dataset's run log)

We need to include counts of these items as a separate thing from the `/activity` response, possibly as part of the proposed `UberData` response that includes high-level meta info about a dataset.

We should also consider why `/activity' has runs and commits mixed together to begin with, and whether it should be split into separate calls for runs and commits.

**Comment by ramfox** [comment]
This can be closed. 

To address each issue:
- the activity endpoint accepts page parameters in the form of `limit` and `offset`. I've currently changed the `fetchDatasetLogs` action to use those instead of `page` and `pageSize`
- We now use the collection to populate the `runCount`, not the size of the log
- We've "beefed up" the `VersionInfo` to include "meta" information about the entire history of the the dataset, including `runCount`, `commitCount`, `issueCount`, `downloadCount`, and `followerCount`. We will possibly create a kind of `Uberdata` structure, but are planning on holding off until we are more settled on the different kinds of things a user may want us to track for them.
- As to the point of having the entire dataset log be returned in one endpoint, we specifically made this change during our last API refactoring, moving from having the two separate `Log` and `History` endpoints, into one `Log` endpoint. The plan was to, in the future, add a "filter" option that will allow you to specify "runs", "commits", or any other options that may end up in the log. So in the future, this filtering will not have to happen on the frontend side, it's just not top priority right now.
