### ISSUE TITLE
Don't show toasts for the active dataset (don't show toasts for the deploy)

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#258]
When deploying, give the user feedback in the modal they are already looking at, there is no need to show toasts for the "initial" run that happens on deploy.

**Comment by ramfox** [comment]
In the future, when we have everything lined up correctly the process for filtering out the appropriate transform events would go as follows:

1) we save a new dataset or update an existing one without running the transform. If we did not have an `InitID` before (because the dataset did not exist) we have one now. This `InitID` will get passed to frontend via the `automation:DeploySaveDatasetEnded` event.
2) we save/update the workflow. If we did not have a `WorkflowID` before (because the workflow did not exist), we have one now. This `WorkflowID` will get passed to the frontend via the `automation:DeploySaveWorkflowEnd`
3) if `run == true`, we create a `RunID` & it gets passed to the frontend via the `automation:DeployRun` event
4) frontend uses the `runID` to filter out the appropriate transform events so we don't get toasts of runs that are happening as part of a deploy

Now, however, we either need to come up with a bandaid for what to do if the dataset is being saved for the first time.

I think there is a simple-ish bandaid we can use on the backend.

Since we know that all we may potentially have "runs" as part of the `Save` portion of our process, we just need to ensure that frontend can get the `runID`, which we should be able to do pretty easily.

So, once we make this fix, the process would go like this when a dataset is deployed for the first time:

1) we get the `runID` from the `automation:DeployStart` event (basically the backend will make a run id early and ensure the save path uses this run id in the transform events)
2) we use that `runID` to filter the events (same as we will in the future when this is set up properly, we are just getting the `runID` at a different time)

backend issue: https://github.com/qri-io/qri/issues/1928

**Comment by chriswhong** [comment]
No longer seeing a toast on initial deploy or re-deploy, closing
