### ISSUE TITLE
Toast identifies the dataset that is running

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#261]
We should be able to see the `username/name`, and perhaps the run number when a toast shows up.  On success or failure, clicking the toast (or a link in the toast) should go to the run log.

**Comment by ramfox** [comment]
So transform start and end events now include an `InitID`. Using that `InitID` you can query the `collection/get` endpoint that can give you the run count and the dataset reference.

Is this enough to go on? I can see us potentially being able to pass the dataset reference in the event as well, but run count would be a much more difficult/gross prospect (based on how we would have to get that information in the backend).

**Comment by ramfox** [comment]
Okay so we actually need to do a bit more work where this is concerned.

1) we now have a scenario where we are using version infos in two different ways:
     a) to populate the collection
     b) to populate run toasts
2) in the second scenario (populating the run toasts) we may need to fetch a specific version info & keep that information around in order to populate the run toast. We should be storing those version infos in the state tree.

This points to me that we need to re-think the way we are storing and fetching version infos from the collection.

Right now, in order to populate the `Collection` full of the datasets in our collection, we fetch from the `/list` endpoint, which returns a paginated list of version infos. We store those version infos in `state.collection.collection` as a map of `initID`s to `versionInfo`s. To populate the `Collection` component, we use `selectCollection` which iterates over the map and returns an array of `versionInfos`.

We need to switch the way we are thinking about this. Rather than having the `state.collection.collection` be every dataset we want to show the user, we should think of `state.collection.collection` be where we store _any version info that we may need to populate different parts of the app_.

- [x] We should add a field `listedIDs` (or if you can think of a better name, I'm open to that as well) to the CollectionState
- [x] When we `loadCollection`, we should still save each version info to the map `state.collection.collection`, but we should also create an array of `initIDs` associated with each of those version infos
- [x] adjust the collection reducer to handle the new way we are thinking about the collection:
```
# in the collection reducer:
# pseudo code
  'API_COLLECTION_REQUEST': (state, action) => {
    // DONT CLEAR THE COLLECTION DURING A REQUEST
    state.listedIDs = []
    state.collectionLoading = true
  }
  'API_COLLECTION_SUCCESS': (state, action) => {
    action.payload.data.forEach((d: VersionInfo) => {
      state.collection[d.initID] = d
      state.collection.listedIDs.push(d.initID)
    })
    state.collectionLoading = false
  },
```
- [x] change `selectCollection` to use the `listedIDs` field to build a list of version infos to return
- [x] create `function selectVersionInfo(initID:string): VersionInfo` selector that can be used to select a version info by its initID
- [x] create `function fetchVersionInfo(initID: string): VersionInfo` action that will fetch from the `collection/get` endpoint
- [x] create `function loadVersionInfo(initID: string): VersionInfo` action that will optionally load a version info from the collection that we already have, or will call `fetchVersionInfo` to fetch it from the back end
- [x] adjust the collection reducer to respond to 'API_VERSIONINFO_REQUEST', 'API_VERSIONINFO_SUCCESS', & 'API_VERSIONINFO_FAILURE', adding a version info into the `state.collection.collection` map on success
- [x] refactor the `runsRef` in `ToastRenderer` to hold more information about the run:
```
# untested/pseudo code
interface RunToastState {
    status: RunStatus
    ref: string
}

const runsRef = useRef({} as Record<string, RunToastState>)
const runs = useSelector(selectRunsFromEventLog)
const initIDs = runs.map((r: Run) => r.initID)

useEffect(() => {
    initIDs.forEach((id: string) => dispatch(loadVersionInfo(id)) )
}, [dispatch, initIDs])
...
...
  runs.forEach((run: Run) => {
    const { id, status, initID } = run

    switch(status) {
      case 'running':
        // only create a new toast if there's no record for this id in runsRef
        if(!runsRef.current[id]) {
        let ref = ''
        if (initId) {
          vi = useSelector(selectVersionInfo(initID))
          ref = vi.username+'/'+vi.name
        }
          runsRef.current[id] = {status, ref}
          toast(<Toast message='Running Workflow...' type='running' ref={ref} />, {
            toastId: id,
            autoClose: false,
          })
        }
      break
     ...
```

I'm sure the above need to be improved on, but basically, rather than keeping a separate store of version infos in the state of the `ToastRenderer`, rely on the state tree to give you the version info information you need.
