### ISSUE TITLE
name editing no longer works

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#293]
I looks like we have lost the ability to click on a dataset name in the header and change it.  Investigate and restore.

**Comment by chriswhong** [comment]
On further investigation, it looks like the way we determine `editable` is depending on `state.dataset` but we made some changes in the recent past that only populate `state.dataset` when using the history view.   `state.dsPrevew` is being used for the time being to store top-level info for the dataset route, but this will probably be changed soon in favor of something nicknamed `Uberdata` that will not be a preview nor a dataset, but high-level info about the dataset the user is currently looking at. 

We should wait until these state refactors are done before looking at this logic to figure out how to calculate `editable`.

```
export const selectSessionUserCanEditDataset = (state: RootState): boolean => {
  const u = selectSessionUser(state)
  if (state.dataset.loading) {
    return false
  }
  // TODO(b5) - this would ideally be checking for an existing dataset ID instead
  // of a path
  if (state.dataset.dataset.path === '') {
    return true
  }
  return u.username === state.dataset.dataset.peername
}
```

**Comment by ramfox** [comment]
Now that we have the "extended" version info, we should be using that to coordinate. It's stored as `dataset.header` in state. can use `selectDatasetHeader` to pull it out of state.

**Comment by boandriy** [comment]
Hey @ramfox, @b5, currently the `selectSessionUserCanEditDataset` is dependent on `state.dataset.loading` which is false (meaning the we can edit the ds name) only on history route. I can make change to add loading state to header request and make it dependent on it instead. this will mean that we will be able to change the dataset name when we go to ds preview page. Let me know what you think.

**Comment by ramfox** [comment]
Sounds like a good approach to me! One thing to pay attention to: what happens if the header fails to load? need to make sure that the app won't crash if the header doesn't load properly.

Chris also brings up a good point: we should only be getting shown the option to "rename" a dataset if it is a dataset that you yourself have created, so if the `dataset.username == session.username`. (this might change in the future as we expand on what it means to "own" a dataset, but for now this is good enough).
