### ISSUE TITLE
/list returns multiple datasets with runStatus: "running"

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#308]
<img width="1101" alt="Home___Qri_Cloud" src="https://user-images.githubusercontent.com/1833820/131013129-3eb2aec6-d229-4068-9a91-2ec89f29e7f9.png">

It looks like changes deployed to rosebud this morning are causing new runs to always show as running in the `/list` response

**Comment by ramfox** [comment]
hey, I tried recreating this locally and on rosebud and my runs are coming back as "succeeded".

In the collection, we only track the status in two places:
1) `ETAutomationWorkflowStarted` events, where we set the `Status` as "running"
2) `ETAutomationWorkflowStopped` events, where we take the `Status` from the event.

I can see two potential things that could have gone wrong:
a) even though the event is a `ETAutomationWorkflowStopped` event, we emit "running" as the `Status` somewhere
b) this transform exits through a codepath that we do not cover by emitting a `,ETAutomationWorkflowStopped`. Since that event is never emitted, the collection never updates the status from "running" to "failed" or "success"

Can I get a copy of the transform being used? I tried to access it via cloud, but it won't load for me.

**Comment by ramfox** [comment]
Okay, I ruled out a bunch of places where this can be going wrong:

1) when we migrate a new collection on backend, we DO NOT check for last run status. We pull from the repo and do not supplement using logbook (although we may want to do this in the future). So this issue does not lie with migrating the collection from repo.
2) there is nothing wrong with the transform itself, locally this runs fine

The `/activity` endpoint pulls from the logbook. It could be that logbook is erroneously keeping track of the status as "running"

This quest, however, has highlighted a bunch of bugs in collection that I will be filing a different issue on.

**Comment by chriswhong** [comment]
Seems to be localized, closing
