### ISSUE TITLE
New Version Preview in Workflow Editor should resemble a version preview from history

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#393]
It should show the commit message, user icon, username, and timestamp.

![image](https://user-images.githubusercontent.com/1833820/136825176-04cad2df-6805-4c0c-b50c-f9c073d961fc.png)

Right now it looks like this:

![image](https://user-images.githubusercontent.com/1833820/136825291-90ea06a4-7cbe-49ec-8595-b2aec65c8c2a.png)

**Comment by boandriy** [comment]
Hey @chriswhong , there are few problems Here.
1. Our sidebar is a bit smaller then sidebar in history tab. So the content is a bit squished ( can be fixed by adding additional props to the `DatasetCommit` component):
![image](https://user-images.githubusercontent.com/22635911/137112358-3898a310-b296-458c-a138-51afb7203f1b.png)
2. we have access to this log data after we deploy the DS. So before that what should I do? When the DS is created and someone runs the dry run, should I simulate the output on FE?

**Comment by chriswhong** [comment]
There is a PR up right now that will prevent the first row (commit title) from wrapping.  I think we can also omit the commit hash from this view, and that should allow it to fit properly.

When the dry run hasn't run yet, this should be "grayed out". We should get a mockup for this from Tefy.

**Comment by dustmop** [comment]
The backend was not including commit title and message for dry runs, but that should now be fixed thanks to https://github.com/qri-io/qri/pull/1947
