### ISSUE TITLE
[workflow]: show relative time since dry run completion in the next version preview

### ISSUE THREAD

**Issue by chriswhong** [qri-io/frontend#485]
![image](https://user-images.githubusercontent.com/1833820/139306277-b9a52a95-b614-4b14-b1d3-cc92fb406a51.png)

**Comment by ramfox** [comment]
So this isn't a "dummy" timestamp, it's a "zero" timestamp. In #509 we now look out for zero timestamps and return "--" rather than the strange "11ymoblahblah" timestamp we were showing before.

I believe when we are at this point in frontend, we also have access to the run start and run stop times. We can mock the commit time by using the run stop time. However, we would need to make a copy of the entire dsPreview & add the stop time to the new object, since I believe it's "read only" at that point.

**Comment by Arqu** [comment]
Yep, this is a bit hard to cover with our current data models. But generally there should always be the expectation that we get an empty timestamp in places which technically should mean we don't have the value.

**Comment by ramfox** [comment]
Yea, I'll have to double check to see why we have `commitTime` as a value rather than a pointer, but I suspect it was designed that way back when a `VersionInfo` corresponded to an actually version (rather than potentially a run or just a description of what is going on in a dataset, like it can be now), which meant that we would ALWAYS have a commit time since every version by necessity would have a commit time.

I vote we adjust it so that `VersionInfo.CommitTime *time.Time`, but I don't think this will be helpful for the current release, since it would cause many changes to our data model and have side effects we need to think through.

**Comment by chriswhong** [comment]
I'll reduce the priority on this, but I would still like to see a real relative timestamp here just so we are consistent with other places in the UI where we show a commit.

**Comment by ramfox** [comment]
Hey, so we actually don't need to get this from the backend, we already have the tools to determine the time, since we get the events on the frontend, and collect the events up when we calculate the `run`, anyway!

Working on this now. Also cleaning up a few missing pieces in our run reducer (not calculating duration)

this goes hand-in-hand with the commit preview not returning the correct username. Just some pipeline issues on the frontend, not something that needs to come from the backend!
